import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import {
  verifyExecutionIntentOffline,
  verifyExecutionTrustRecordOffline,
} from "../src/parmana/OfflineVerifier.js";
import type {
  ExecutionIntent,
  ExecutionTrustRecord,
} from "../src/parmana/types.js";
import {
  isMlDsa65Supported,
  ML_DSA_65_SKIP_REASON,
} from "../src/support/MlDsaSupport.js";

/**
 * Compatibility with artifacts signed by Parmana's own
 * @parmana/crypto code, not by this library.
 *
 * tests/fixtures/parmana-artifacts.json is generated by
 * scripts/generate-parmana-fixtures.mts, which imports
 * Parmana's real canonical views, hasher, Ed25519/ML-DSA-65
 * providers, hybrid signer and KMS commitment. If Parmana
 * changes what it signs, regenerate the fixture: these
 * tests then show exactly where this library has drifted.
 */
const fixture = JSON.parse(
  readFileSync(
    new URL("./fixtures/parmana-artifacts.json", import.meta.url),
    "utf8",
  ),
) as {
  publicKeys: Record<string, string>;
  legacyRecord: ExecutionTrustRecord;
  hybridRecord: ExecutionTrustRecord;
  largeKmsRecord: ExecutionTrustRecord;
  largeLocalRecord: ExecutionTrustRecord;
  intent: ExecutionIntent;
};

describe("Parmana-signed artifacts", () => {
  it("verifies a legacy Ed25519 Execution Trust Record", async () => {
    const result = await verifyExecutionTrustRecordOffline(
      fixture.legacyRecord,
      fixture.publicKeys,
    );

    expect(result.errors).toEqual([]);
    expect(result.valid).toBe(true);
  });

  it("verifies a large record signed through KMS as a commitment", async () => {
    const result = await verifyExecutionTrustRecordOffline(
      fixture.largeKmsRecord,
      fixture.publicKeys,
    );

    expect(result.errors).toEqual([]);
    expect(result.valid).toBe(true);
  });

  it("verifies a large record signed raw by a local key", async () => {
    const result = await verifyExecutionTrustRecordOffline(
      fixture.largeLocalRecord,
      fixture.publicKeys,
    );

    expect(result.errors).toEqual([]);
    expect(result.valid).toBe(true);
  });

  it("verifies an Execution Intent", async () => {
    const result = await verifyExecutionIntentOffline(
      fixture.intent,
      fixture.publicKeys,
    );

    expect(result.errors).toEqual([]);
    expect(result.valid).toBe(true);
  });

  it("rejects a Parmana record with a single changed field", async () => {
    const record = fixture.legacyRecord;

    const result = await verifyExecutionTrustRecordOffline(
      { ...record, businessTransactionId: "btx-other" },
      fixture.publicKeys,
    );

    expect(result.valid).toBe(false);
  });

  it.skipIf(!isMlDsa65Supported())(
    `verifies a hybrid Ed25519 + ML-DSA-65 record${isMlDsa65Supported() ? "" : ` [SKIPPED: ${ML_DSA_65_SKIP_REASON}]`}`,
    async () => {
      const result = await verifyExecutionTrustRecordOffline(
        fixture.hybridRecord,
        fixture.publicKeys,
      );

      expect(result.errors).toEqual([]);
      expect(result.valid).toBe(true);
      expect(result.hybridSignaturesValid).toBe(true);
    },
  );
});
